export { header } from './header';
export { footer } from './footer';
export { hero } from './hero';
export { credibilityLine } from './credibilityLine';
export { howItWorks } from './howItWorks';
import product from './product';
export { product };
import conditions from './conditions';
export { conditions };
import brief from './brief';
export { brief };
import { vsTable } from './vsTable';
export { vsTable };
import { pricing } from './pricing';
export { pricing };
import { finalCTA } from './finalCTA';
export { finalCTA };
